title: 'Public Speaking: Part 1'
tagline: What makes a good public speaker?
description: >-
  In this course, we'll take a look at examples of what makes a good
  presenter,and use these examples to show what small changes you can make to
  your presenting style to stand out from the crowd.
template:
  repo: public-speaking-part-one-template
  name: public-speaking-part-one
  description: >-
    In this course, we'll take a look at examples of what makes a good
    presenter,and use these examples to show what small changes you can make to
    your presenting style to stand out from the crowd.
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
